# Generated by Django 6.0.6 on 2026-07-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_stripe_charge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('cash', 'Naqd pul')], max_length=20),
        ),
    ]
