# Generated by Django 6.0.6 on 2026-08-05 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otpcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpcode',
            old_name='phone_numebr',
            new_name='phone_number',
        ),
    ]
