# Generated by Django 6.0.6 on 2026-08-28 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_phone_numebr_otpcode_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
