# Generated by Django 6.0.6 on 2026-06-29 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InsuranceClaim',
        ),
    ]
