# Generated by Django 6.0.6 on 2026-08-28 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_doctorpayout_amount_alter_invoice_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorpayout',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
    ]
