# Generated by Django 6.0.6 on 2026-09-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_doctorpayout_options_alter_invoice_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorPayout',
        ),
    ]
