# Generated by Django 6.0.6 on 2026-06-27 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=225)),
                ('name_ru', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=225)),
                ('name_ru', models.CharField(max_length=225)),
                ('contact', models.CharField(blank=True, max_length=225)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('logo', models.URLField(blank=True)),
                ('webiste', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=225)),
                ('phone_number', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.clinictype')),
                ('medical_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.medicalcenter')),
            ],
        ),
    ]
