# Generated by Django 6.0.6 on 2026-06-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalcenter',
            old_name='webiste',
            new_name='website',
        ),
    ]
