# Generated by Django 6.0.6 on 2026-08-28 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_rename_webiste_medicalcenter_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='clinictype',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='medicalcenter',
            options={'ordering': ['-created_at']},
        ),
    ]
