# Generated by Django 6.0.6 on 2026-06-29 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_alter_appointment_updated_at'),
        ('doctors', '0003_doctor_is_active_alter_doctor_gender'),
        ('patients', '0003_patient_national_id_alter_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_uz', models.TextField()),
                ('diagnosis_ru', models.TextField(blank=True)),
                ('notes_uz', models.TextField(blank=True)),
                ('notes_ru', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name_uz', models.CharField(max_length=255)),
                ('medication_name_ru', models.CharField(blank=True, max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency_uz', models.CharField(max_length=255)),
                ('frequency_ru', models.CharField(blank=True, max_length=255)),
                ('duration_days', models.PositiveIntegerField()),
                ('notes_uz', models.TextField(blank=True)),
                ('notes_ru', models.TextField(blank=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
        ),
    ]
