# Generated by Django 6.0.6 on 2026-08-28 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='prescriptionitem',
            options={'ordering': ['-id']},
        ),
    ]
