# Generated by Django 6.0.6 on 2026-08-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_rating_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(choices=[('video', 'Video'), ('voice', 'Voice'), ('chat', 'Chat')], default='video', max_length=225),
        ),
    ]
