# Generated by Django 6.0.6 on 2026-08-28 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_appointment_consultation_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at']},
        ),
    ]
