# Generated by Django 6.0.6 on 2026-09-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_appointment_options_alter_rating_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='video_room_token',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
