import uuid
from django.db import migrations

def fill_tokens(apps, schema_editor):
    Appointment = apps.get_model('appointments', 'Appointment')
    for appt in Appointment.objects.filter(video_room_token__isnull=True):
        appt.video_room_token = uuid.uuid4()
        appt.save(update_fields=['video_room_token'])

def noop(apps, schema_editor):
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('appointments', '0010_appointment_video_room_token'),
    ]
    operations = [
        migrations.RunPython(fill_tokens, noop),
    ]# Generated by Django 6.0.6 on 2026-09-13 08:19

