# Generated by Django 6.0.6 on 2026-09-13 08:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_alter_appointment_video_room_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='video_room_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
