# Generated by Django 6.0.6 on 2026-06-15 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=225)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rannk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ranktype')),
            ],
        ),
    ]
