# Generated by Django 6.0.6 on 2026-07-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankprice',
            name='consultation_type',
            field=models.CharField(choices=[('video', 'Video'), ('voice', 'Voice'), ('chat', 'Chat'), ('in_person', 'In-person')], default='in_person', max_length=225),
        ),
    ]
