# Generated by Django 6.0.6 on 2026-07-08 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rankprice_consultation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciality',
            name='description',
        ),
    ]
