# Generated by Django 6.0.6 on 2026-08-28 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_rankprice_consultation_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rankprice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ranktype',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='speciality',
            options={'ordering': ['-id']},
        ),
    ]
