# Generated by Django 6.0.6 on 2026-06-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=225)),
                ('name_ru', models.CharField(max_length=225)),
                ('gender', models.CharField(blank=True, choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], default='erkak', max_length=225)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(blank=True, max_length=225)),
                ('address', models.CharField(blank=True, max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
