# Generated by Django 6.0.6 on 2026-07-11 01:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_name_ru_alter_patient_name_uz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="JSHSHIR 14 xonali raqamdan iborat bo'lishi kerak.", regex='^\\d{14}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=225, validators=[django.core.validators.RegexValidator(message="Telefon raqam +998XXXXXXXXX formatida bo'lishi kerak.", regex='^\\+998\\d{9}$')]),
        ),
    ]
