# Generated by Django 6.0.6 on 2026-06-27 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.CharField(blank=True, max_length=225)),
                ('name_uz', models.CharField(max_length=225)),
                ('name_ru', models.CharField(max_length=225)),
                ('bio_uz', models.TextField(blank=True)),
                ('bio_ru', models.TextField(blank=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('avatar', models.URLField(blank=True)),
                ('gender', models.CharField(blank=True, choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], default='erkak', max_length=225)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic')),
                ('rank_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ranktype')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.speciality')),
            ],
        ),
    ]
