# Generated by Django 6.0.6 on 2026-07-11 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_is_active_alter_doctor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='name_ru',
            field=models.CharField(max_length=225, validators=[django.core.validators.RegexValidator(message="Ism faqat harflardan iborat bo'lishi kerak.", regex="^[A-Za-zА-Яа-яЁёʻʼ'\\-\\s]+$")]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name_uz',
            field=models.CharField(max_length=225, validators=[django.core.validators.RegexValidator(message="Ism faqat harflardan iborat bo'lishi kerak.", regex="^[A-Za-zА-Яа-яЁёʻʼ'\\-\\s]+$")]),
        ),
    ]
