# Generated by Django 6.0.6 on 2026-07-11 01:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_name_ru_alter_doctor_name_uz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=225, validators=[django.core.validators.RegexValidator(message="Telegram username noto'g'ri formatda.", regex='^@?[A-Za-z0-9_]{5,32}$')]),
        ),
    ]
