# Generated by Django 6.0.6 on 2026-07-14 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_doctor_telegram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='auto_payout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='bank_name',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='doctor',
            name='iban',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='doctor',
            name='revenue_percentage',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
