# Generated by Django 6.0.6 on 2026-08-28 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_doctor_auto_payout_doctor_bank_name_doctor_iban_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'ordering': ['-id']},
        ),
    ]
