# Generated by Django 6.0.6 on 2026-09-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_alter_doctor_options_alter_doctorschedule_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='auto_payout',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='revenue_percentage',
        ),
    ]
