# Generated by Django 6.0.6 on 2026-06-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('appointment_created', 'Appointment Created'), ('status_changed', 'Status Changed'), ('reminder', 'Reminder')], max_length=225)),
                ('template_text', models.TextField()),
            ],
        ),
    ]
