# Generated by Django 6.0.6 on 2026-06-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotficationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push')], max_length=225)),
                ('is_sent', models.BooleanField(default=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('body_uz', models.TextField()),
                ('body_ru', models.TextField()),
                ('type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push')], max_length=225)),
            ],
        ),
    ]
